name: Auto Deployment to DockerHub & AWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    name: backend_build
    runs-on: ubuntu-latest
    env: 
      working-directory: |
          ./backend
          ./nginx
          ./frontend
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: after_success
      run: |
           docker build -t brinst07/docker-backend ./backend

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and release to DockerHub
      run: docker push brinst07/docker-backend
      working-directory: ${{env.working-directory}}

  frontend:
    name: frontend_build
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
      
    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:
    - name: before_install
      run: docker build -t brinst07/react-test-app -f ../frontend/Dockerfile.dev ./frontend

    - name: script
      run: docker run -e CI=true brinst07/react-test-app npm test

    - name: after_success
      run: |
           docker build -t brinst07/docker-frontend ./frontend
