name: Auto Deployment to DockerHub & AWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: docker_build
    runs-on: ubuntu-latest
    env:
      working-directory: |
        ./backend
        ./nginx
        ./frontend
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t brinst07/docker-backend ./backend
          docker build -t brinst07/docker-frontend ./frontend
          docker build -t brinst07/docker-nginx ./nginx

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: backend release to DockerHub
        run: docker push brinst07/docker-backend
        working-directory: ./backend

      - name: frontend release to DockerHub
        run: docker push brinst07/docker-frontend
        working-directory: ./frontend

      - name: nginx release to DockerHub
        run: docker push brinst07/docker-nginx
        working-directory: ./nginx